### ISSUE TITLE
Adding my own courses

### ISSUE THREAD

**Issue by jubalh** [chickendude/GlossikaNativeGLS#1]
I have the italian and spanish courses.
Would like to add them to the script too.

What does `'F1': [50, 442],` stand for?

**Comment by jubalh** [comment]
I take it this are the page numbers the actual sentences start/end.

However I'm not sure how to call the script.
When I got Glossika the dir structure was like this:

```
Italienisch ->
  DEIT-F123-EBK -> GLOSSIKA-DEIT-F{1,2,3}-EBK.pdf
  DEIT-F1-GMS -> GMS-{A,B,C} -> DEIT-F1-GMS-A-0001.mp3 (etc)
  DEIT-F1-GSR -> DEIT-F1-GSR-DAY001.mp3 (etc)
```

No matter how I call the script, no matter whether I use python2 or python3 I get:
```
  File "./split_text.py", line 52
SyntaxError: Non-ASCII character '\xe7' in file ./split_text.py on line 52, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

https://github.com/chickendude/GlossikaNativeGLS/pull/2 should solve this.

However I'm still not sure how the script is supposed to be called.

**Comment by chickendude** [comment]
Sorry, it's not very well documented! Yes, those are the page numbers where the sentences start and end. There aren't any parameters, it just checks the files in the PATH directory (line 117) and goes through all PDFs that it can find a match for and splits them "automatically". Most languages have three types, base language, target language, and ipa. You need to put the actual text thatit should match. The Chinese courses are a bit of a special case so i handle those separately, but German-Italian should be pretty easy to add.

I have all the PDFs put in the 'texts' folder, then i run the script `./split_text.py`. You can change the folder if you like, though. 

EDIT: And the PDF library only works on Linux. And i'm using Python 3.

**Comment by jubalh** [comment]
> I have all the PDFs put in the 'texts' folder, then i run the script ./split_text.py. You can change the folder if you like, though.

Alright, thanks!

> EDIT: And the PDF library only works on Linux. And i'm using Python 3.

I'm aware :-)

**Comment by jubalh** [comment]
I'm a step further now but still have some issue, I will create a WIP PR so we can discuss there and you can see the code.

https://github.com/chickendude/GlossikaNativeGLS/pull/3

**Comment by chickendude** [comment]
Nice, if you have any issues with the other parts (e.g. extracting the audio) let me know!

**Comment by jubalh** [comment]
Yeah, actually:
Since ACCEPTED_PDFS is not used anymore I guess this is true for similar variables in the other scripts.

But I guess it would be good to note down with which courses the scripts should work or where tested to work. Either by mentioning in the readme or by listing (printing) them in the script. What do you think?

**Comment by jubalh** [comment]
Another PR to remove the unused var in split_audio.py https://github.com/chickendude/GlossikaNativeGLS/pull/5

**Comment by jubalh** [comment]
We have `split_audio.py` and `split_gms.py`, in case that the former is used with the GSR files maybe `split_gsr.py` would be a clearer name :)

When I run that one, after changing this:
```
@@ -113,7 +113,7 @@ def split_audio(gtl_path, gms_path, language, book, base_folder, unique_folder,
 
 
 def split():
-       split_audio(GTL_PATH, PATH, 'ENES', 'F1', EXPORT_PATH, '')
+       split_audio(GTL_PATH, PATH, 'DEIT', 'F1', EXPORT_PATH, '')
```

Nothing seems to happen. Could you give me some  hint?

**Comment by chickendude** [comment]
Yeah, before i was using sentence markings taken manually via Audacity, then i just used the silence to split them, it's not always 100% but for most courses, even triangulations, it works fine. The new one is split_gms.py, the older version with the sentence timings is split_audio.py. So you should be using split_gms.py. I pulled the path variable (where all the GMS-B files should be) into a global variable in split_gms.py, i should probably remove split_audio.py altogether, but i spent so much time getting the timings... Anyway, try pulling the latest changes and be sure to add the language pair to the LANGUAGES dictionary at the top. Since some languages have three letters, you can't just split the language pairs/sets into sets of two letters, unfortunately.

Ah, and the actual script is really slow, it may take 5-10 minutes to get through, but it should split it into DE and IT subfolders in the output folder. The output should let you know if there was an err splitting a file into individual sentences. It should work with GMS B or C files, so if you split other DE courses you won't have to wait for the DE stuff to split again.

**Comment by jubalh** [comment]
Thanks for the info.
I gree that it does not hurt to have `split_audio.py` stay here. Maybe just a notice/note would be enough that actually `split_gms.py` is what should be used :-) In the readme still `split_audio.py` is mentioned as the main thing I think.

**Comment by chickendude** [comment]
Yeah, i opened an issue to update the README this weekend hopefully when i get some time :)

**Comment by jubalh** [comment]
It seems it skipped every file:

```
python3 split_gms.py                                   
Analyzing 'files/DEIT-F1-GMS-B-0001.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0051.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0101.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0151.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0201.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0251.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0301.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0351.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0401.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0451.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0501.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0551.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0601.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0651.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0701.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0751.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0801.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0851.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0901.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
Analyzing 'files/DEIT-F1-GMS-B-0951.mp3'
** ERR: INVALID NUMBER OF CHUNKS (101), SKIPPING **
```

I put the GMS-B files in `./files` and ran the script. All my GMS-B file start with `The GMS Method. Fluency 1. Deutsch - Italiano`, and only then the sentences begin. Just mentioning in case this matters. I'm aware that Glossika resources got updated over time and it might be that we are working with different versions.

**Comment by jubalh** [comment]
Only change so far in `split_gms.py` I have locally is this:
```
--- a/split_gms.py
+++ b/split_gms.py
@@ -22,6 +22,7 @@ LANGUAGES = {
        'ENZT': ('EN', 'ZT'),
        'PBESM': ('PB', 'ESM'),
        'PBENFR': ('PB', 'EN', 'FR'),
+       'DEIT': ('DE', 'IT'),
 }
```

**Comment by chickendude** [comment]
It's incorrectly reading something, it should be 100 chunks, my guess is
that it's reading an extra line at the start or end (those "brought to you
by Glossika" things).

Try adding one to the "len(languages)" in the line "chunks = chunks[len(languages):-2]" so it looks like "len(languages)+1".

**Comment by jubalh** [comment]
That worked, thank you.
Created a PR which adds support for DEIT in `split_gms.py` thus completing DEIT support.

**Comment by jubalh** [comment]
Merged. DEIT added :-)

**Comment by jubalh** [comment]
@chickendude After running the create_gls.py I ended up with DE-F1.gls - DE-F3.gls and It-F1.gls - IT-F3.gls
Put them on the phone and wanted to import them with Natibo 0.2.4. It hangs forever at "Opening File".

In the YT video which is linked in the readme of Natibo I see that the gls there is actually named `EN-ZS-F1.gls`.
Did I do something wrong? Or is that video just from an older state of the project?

**Comment by chickendude** [comment]
Sorry @jubalh missed this message somehow, the YouTube video is using an older version where both languages were packed in one file. Now i've separated them into different files to make adding multiple languages easier/faster.

Are you still having trouble loading the files? Sometimes it gets stuck opening the file for a while (up to maybe 30 seconds or so), sometimes it loads very quickly, i'm not really sure what causes it, maybe loading the file into RAM? And are you familiar with Android development/debugging?

You can try opening the .gls files (they are just renamed zip files) and making sure the filenames are correct and the sentences are all there in the .gsp file. Is it an issue with all the .gls files?
