### ISSUE TITLE
ModuleNotFoundError: No module named 'pdftotext' even when installed

### ISSUE THREAD

**Issue by RpiDude** [chickendude/GlossikaNativeGLS#9]
I have installed pdftotext as seen here when typing the command

GlossikaNativeGLS$ pdftotext
pdftotext version 0.74.0
Copyright 2005-2019 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
Usage: pdftotext [options] <PDF-file> [<text-file>]

But when I do this your script doesn't find the module:

GlossikaNativeGLS$ python3 ./split_text.py 
Traceback (most recent call last):
  File "./split_text.py", line 5, in <module>
    import pdftotext
ModuleNotFoundError: No module named 'pdftotext'

How to solve?, many thanks.

**Comment by RpiDude** [comment]
Never mind solved it, have to install it using pip3 and not using normal pip

**Comment by jubalh** [comment]
> Never mind solved it, have to install it using pip3 and not using normal pip

If you run the scripts with python 3 then you also need the dependencies for python3, thus you need pip3.
Please close this issue if you solved it.
